### ISSUE TITLE
images are not reachable / HTTP 404

### ISSUE THREAD

**Issue by basisbit** [booru/philomena#30]
**Describe the bug**
Thumbnail images can not be loaded by the client any more because the nginx container can't access the image files any more and thus returns HTTP 404.
This was caused by the changes Dockerfile changes in https://github.com/booru/philomena/commit/bc193bf097fca5fb72f216a35f9cbbd5bfa75a9d .

**To Reproduce**
1. Start booru
2. Open main page
3. look at any image.

**Expected behavior**
Images should be loaded by the client.

**Screenshots**
![image](https://user-images.githubusercontent.com/10870269/87998419-23d3ba80-caf8-11ea-9674-83a9d65b53a2.png)

**Additional context**
As a workaround, reverting the mentioned commit "fixes" the problem: `git revert -n bc193bf`
The /srv/assets/static/system/images folder from container app does not appear in container web any more because of some changes in that commit.

**Comment by cultpony** [comment]
I'll have a look at it, probably an issue on how the volume is mounted.
