### ISSUE TITLE
Avatar upload error message is confusing

### ISSUE THREAD

**Issue by ErikMcClure** [booru/philomena#56]
**Describe the bug**
If the avatar file is larger than 300000 bytes, this error message is produced: "Avatar size must be less than or equal to 300000"

**To Reproduce**
Upload an avatar that's too large.

**Expected behavior**
This error message is confusing because it's not clear what "300000" is, or what "size" refers to. Instead, it should say something like "Avatar filesize must be less than or equal to 300kb", which is more clear.

**Screenshots**
![image](https://user-images.githubusercontent.com/3387013/89598242-2b41d600-d811-11ea-81e7-8f58f4dfb0dd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Comment by Belomi** [comment]
In [this template](https://github.com/booru/philomena/blob/master/lib/philomena_web/templates/avatar/edit.html.slime#L23) you could prefix the message from the changeset with the appropriate units or even replace the message entirely with plain text (though if you did this you would have to keep in in sync with every change to the allowed dimensions). Something such as:
```
            - avatar_size_cond = if :avatar_size do "#{:avatar_size} bytes" else nil
            - avatar_width_cond = if :avatar_width do "#{:avatar_width}px" else nil
            - avatar_height_cond = if :avatar_height do "#{:avatar_height}px" else nil
            = error_tag f, avatar_size_cond
            = error_tag f, avatar_width_cond
            = error_tag f, avatar_height_cond
```
or even:
```
            - avatar_size_msg = "Avatar size must not exceed 300kb"
            - avatar_width_msg = "Avatar width must not exceed 1,000px"
            - avatar_height_msg = "Avatar height must not exceed 1,000px"
            - avatar_size_cond = if :avatar_size do avatar_size_msg else nil
            - avatar_width_cond = if :avatar_width do avatar_width_msg else nil
            - avatar_height_cond = if :avatar_height do avatar_height_msg else nil
            = error_tag f, avatar_size_cond
            = error_tag f, avatar_width_cond
            = error_tag f, avatar_height_cond
```

**Comment by alamais-df** [comment]
I believe there's a better way to process these errors built into phoenix, but I don't understand it yet.

**Comment by Belomi** [comment]
> I believe there's a better way to process these errors built into phoenix, but I don't understand it yet.

I think that I have found the way to do this but I lack the ability to spin up a development instance to test it. I changed (this line)[https://github.com/booru/philomena/blob/master/lib/philomena/users/user.ex#L380] to:
```elixir
|> validate_avatar_size(:avatar_size)
```
and then add the following function below to act as the validator:
```elixir
def validate_avatar_size(changeset, field) when is_atom(field) do
    validate_change(changeset, field, fn (current_field, value) ->
      if 0 < value and value < 300_000 do
        [{current_field, "Avatar size must be less than 300kb"}]
      else 
        []
      end
    end)
  end
```

**Comment by Belomi** [comment]
Should be closed as per the above merge.
