### ISSUE TITLE
New images hidden by default

### ISSUE THREAD

**Issue by ErikMcClure** [booru/philomena#59]
**Describe the bug**
New images without much engagement are hidden by the default filter to prevent mistagging. There is no indication of this happening anywhere in the UI.

**To Reproduce**
1. Set your filter to "Default"
2. Upload any image
3. Search for it
4. Observe that it doesn't appear

**Expected behavior**
Your image should show up when you search for it.

**Additional context**
This might be intended behavior, but it needs some sort of indicator on the image saying "this image is being hidden from search results for being too new. It will show up under the default filter later"

**Comment by basisbit** [comment]
this seems to be caused by the filters which are used on your booru. A Site notice or changing these filters might help.

**Comment by ErikMcClure** [comment]
This was fixed by adding a custom upload message to clarify the intended behavior
