### ISSUE TITLE
Random pages of images

### ISSUE THREAD

**Issue by Meganought** [booru/philomena#80]
**Is your feature request related to a problem? Please describe.**
There is already a lot of initial images uploaded to the site, and finding gems in a 10k image upload is hard. Making a page of random images would allow folks to find great images faster.

**Describe the solution you'd like**
Simple really, a "random page" button that gives you a page of random images. Possibly also an "im feeeling lucky" button when searching for a specific tag that does the same thingm, but within that tag's restrictions, I.E. a page of random pinkie pie images

**Describe alternatives you've considered**
I guess you could just... not add this. Thats an alternative.

**Comment by Pathos14489** [comment]
When searching, you can select Random as a search type. It will show you a random page that's based on your search results. Which, you can use the * wildcard to randomly search everything on the booru. 

-

If you wanted to add this, you could go to your `lib\philomena_web\templates\layout\_header_navigation.html.slime`, and add something like:

`a.header__link href="/search?q=*&sf=random"`
`  | Random Results`

...to the bottom, that should give you exactly what you're asking for.

**Comment by basisbit** [comment]
this was actually already implemented by d71a7ff9d57a0f6f40bbc40731f2c6f2f3cc4660 two days ago.
Result looks like this:
![image](https://user-images.githubusercontent.com/10870269/92180498-78808a00-ee47-11ea-849f-59eee214eac0.png)
